# **Data Cleaning**

**Project**: Airbnb Market Segmentation Analisys \
**Goal**: Clean the listings and reviews dataset for future analisys.

### 1. Imports & environment setup

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
# Base path configuration
BASE_PATH = Path.cwd().parent

### 2. Data Loading

In [3]:
listings_raw = pd.read_csv(BASE_PATH / "data" / "raw" / "listings.csv")
reviews_raw = pd.read_csv(BASE_PATH / "data" / "raw" / "reviews.csv")

#### 2.1 Listings dataframe

In [4]:
listings_raw.head(8)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2737,https://www.airbnb.com/rooms/2737,20250914152919,2025-09-15,city scrape,"Elif's room in cozy, clean flat.",10 min by bus you can get to Piazza Venezia or...,It used to be an industrial area until late 80...,https://a0.muscache.com/pictures/41225252/e955...,3047,...,5.00,4.40,4.40,NaN,f,6,0,6,0,0.04
1,11834,https://www.airbnb.com/rooms/11834,20250914152919,2025-09-15,city scrape,"Charming Boschetto Studio, Rome",Fantastic apartment in the Monti district. The...,"""Monti"" with its narrow cobblestone alleys, cr...",https://a0.muscache.com/pictures/miso/Hosting-...,44552,...,4.96,4.99,4.81,IT058091C29VJSIZQZ,f,1,1,0,0,1.62
2,12398,https://www.airbnb.com/rooms/12398,20250914152919,2025-09-15,city scrape,Casa Donatello - Home far from Home,Casa Donatello is a newly renovated two-bedroo...,You are at 15 minutes walking distance from hi...,https://a0.muscache.com/pictures/miso/Hosting-...,11756,...,5.00,4.89,4.83,it058091c2kv6epw8f,f,1,1,0,0,0.47
3,19965,https://www.airbnb.com/rooms/19965,20250914152919,2025-09-15,city scrape,S. Peter's Square 5 Min WALK bright and quite ...,AT ONLY 5 MINUTES WALK to S.Peter's Basilica S...,Prati is a famous neighbourhood (rione of Rome...,https://a0.muscache.com/pictures/hosting/Hosti...,75450,...,4.90,4.90,4.54,IT058091C20YD35BX2,t,3,3,0,0,1.07
4,19967,https://www.airbnb.com/rooms/19967,20250914152919,2025-09-15,city scrape,*In front Vatican Museums 2 bedrooms quite bri...,"IN FRONT of the Vatican Museums entrance, at O...",Prati is a famous neighbourhood (rione of Rome...,https://a0.muscache.com/pictures/hosting/Hosti...,75450,...,4.80,4.85,4.28,IT058091C20YD35BX2,t,3,3,0,0,0.32
5,20534,https://www.airbnb.com/rooms/20534,20250914152919,2025-09-15,city scrape,DormiRoma - Cedro 1 Apartment - Trastevere,Cedro 1 Apartment is located in a beautiful s...,"Trastevere, the heart of the city, home to maj...",https://a0.muscache.com/pictures/miso/Hosting-...,77540,...,4.79,4.92,4.27,IT058091B4I3RFDVLG,t,5,5,0,0,0.27
6,20587,https://www.airbnb.com/rooms/20587,20250914152919,2025-09-15,city scrape,DormiRoma - Cedro 4 Apartment - Trastevere,Cedro 4 Apartment is located in a beautiful se...,"Trastevere, the heart of the city, home to maj...",https://a0.muscache.com/pictures/miso/Hosting-...,77540,...,4.94,4.89,4.70,IT058091B4PUG96AR4,t,5,5,0,0,0.48
7,20699,https://www.airbnb.com/rooms/20699,20250914152919,2025-09-15,city scrape,Vintage Suite w/ Private Bath by Esquiline Suites,This bright and elegant Vintage Suite by Esqui...,The multi-ethnic neighborhood of Esquilino is ...,https://a0.muscache.com/pictures/31060743/8d30...,78287,...,4.95,4.55,4.77,IT058091C1AXWLCJ7C,t,8,2,6,0,3.89

In [5]:
listings_raw.shape

(37652, 79)

In [6]:
listings_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 37652 entries, 0 to 37651
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            37652 non-null  int64
 1   listing_url                                   37652 non-null  str
 2   scrape_id                                     37652 non-null  int64
 3   last_scraped                                  37652 non-null  str
 4   source                                        37652 non-null  str
 5   name                                          37652 non-null  str
 6   description                                   36703 non-null  str
 7   neighborhood_overview                         17721 non-null  str
 8   picture_url                                   37652 non-null  str
 9   host_id                                       37652 non-null  int64
 10  host_url                                      37652 non-null  str
 11  host_name                                     37644 non-null  str
 12  host_since                                    37643 non-null  str
 13  host_location                                 27791 non-null  str
 14  host_about                                    17397 non-null  str
 15  host_response_time                            30861 non-null  str
 16  host_response_rate                            30861 non-null  str
 17  host_acceptance_rate                          33814 non-null  str
 18  host_is_superhost                             35456 non-null  str
 19  host_thumbnail_url                            37643 non-null  str
 20  host_picture_url                              37643 non-null  str
 21  host_neighbourhood                            12241 non-null  str
 22  host_listings_count                           37643 non-null  float64
 23  host_total_listings_count                     37643 non-null  float64
 24  host_verifications                            37643 non-null  str
 25  host_has_profile_pic                          37643 non-null  str
 26  host_identity_verified                        37643 non-null  str
 27  neighbourhood                                 17721 non-null  str
 28  neighbourhood_cleansed                        37652 non-null  str
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      37652 non-null  float64
 31  longitude                                     37652 non-null  float64
 32  property_type                                 37652 non-null  str
 33  room_type                                     37652 non-null  str
 34  accommodates                                  37652 non-null  int64
 35  bathrooms                                     33660 non-null  float64
 36  bathrooms_text                                37618 non-null  str
 37  bedrooms                                      36804 non-null  float64
 38  beds                                          33638 non-null  float64
 39  amenities                                     37652 non-null  str
 40  price                                         33564 non-null  str
 41  minimum_nights                                37652 non-null  int64
 42  maximum_nights                                37652 non-null  int64
 43  minimum_minimum_nights                        37631 non-null  float64
 44  maximum_minimum_nights                        37631 non-null  float64
 45  minimum_maximum_nights                        37631 non-null  float64
 46  maximum_maximum_nights                        37631 non-null  float64
 47  minimum_nights_avg_ntm                        37652 non-null  float64
 48  maximum_nights_avg_ntm                        37652 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              37058 non-null  str
 51  availability_30                               37652 non-null  int64
 52  availability_60                               37652 non-null  int64
 53  availability_90                               37652 non-null  int64
 54  availability_365                              37652 non-null  int64
 55  calendar_last_scraped                         37652 non-null  str
 56  number_of_reviews                             37652 non-null  int64
 57  number_of_reviews_ltm                         37652 non-null  int64
 58  number_of_reviews_l30d                        37652 non-null  int64
 59  availability_eoy                              37652 non-null  int64
 60  number_of_reviews_ly                          37652 non-null  int64
 61  estimated_occupancy_l365d                     37652 non-null  int64
 62  estimated_revenue_l365d                       33564 non-null  float64
 63  first_review                                  32255 non-null  str
 64  last_review                                   32255 non-null  str
 65  review_scores_rating                          32255 non-null  float64
 66  review_scores_accuracy                        32253 non-null  float64
 67  review_scores_cleanliness                     32254 non-null  float64
 68  review_scores_checkin                         32253 non-null  float64
 69  review_scores_communication                   32254 non-null  float64
 70  review_scores_location                        32252 non-null  float64
 71  review_scores_value                           32253 non-null  float64
 72  license                                       34589 non-null  str
 73  instant_bookable                              37652 non-null  str
 74  calculated_host_listings_count                37652 non-null  int64
 75  calculated_host_listings_count_entire_homes   37652 non-null  int64
 76  calculated_host_listings_count_private_rooms  37652 non-null  int64
 77  calculated_host_listings_count_shared_rooms   37652 non-null  int64
 78  reviews_per_month                             32255 non-null  float64
dtypes: float64(24), int64(20), str(35)
memory usage: 22.7 MB

In [7]:
listings_raw.describe(include = 'all')

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.765200e+04,37652,3.765200e+04,37652,37652,37652,36703,17721,37652,3.765200e+04,...,32254.000000,32252.000000,32253.000000,34589,37652,37652.000000,37652.000000,37652.000000,37652.000000,32255.000000
unique,NaN,37652,NaN,2,2,36682,33713,15191,37344,NaN,...,NaN,NaN,NaN,26958,2,NaN,NaN,NaN,NaN,NaN
top,NaN,https://www.airbnb.com/rooms/2737,NaN,2025-09-15,city scrape,Appartamento,Relax in this peaceful and centrally-located p...,Located in the north of the city center Monti ...,https://a0.muscache.com/pictures/miso/Hosting-...,NaN,...,NaN,NaN,NaN,"I applied for a CIN, but haven’t received it yet",t,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,33064,33668,18,77,15,12,NaN,...,NaN,NaN,NaN,337,22855,NaN,NaN,NaN,NaN,NaN
mean,7.461415e+17,NaN,2.025091e+13,NaN,NaN,NaN,NaN,NaN,NaN,2.611336e+08,...,4.856055,4.753798,4.686264,NaN,NaN,9.467598,7.847657,1.527276,0.027701,1.744446
std,5.767852e+17,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,2.432036e+08,...,0.299506,0.317206,0.361069,NaN,NaN,27.352151,27.028811,3.706959,0.540813,1.626930
min,2.737000e+03,NaN,2.025091e+13,NaN,NaN,NaN,NaN,NaN,NaN,2.353000e+03,...,1.000000,1.000000,1.000000,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.892659e+07,NaN,2.025091e+13,NaN,NaN,NaN,NaN,NaN,NaN,2.960476e+07,...,4.830000,4.650000,4.600000,NaN,NaN,1.000000,1.000000,0.000000,0.000000,0.440000
50%,9.477797e+17,NaN,2.025091e+13,NaN,NaN,NaN,NaN,NaN,NaN,1.757405e+08,...,4.950000,4.840000,4.760000,NaN,NaN,2.000000,1.000000,0.000000,0.000000,1.260000
75%,1.269260e+18,NaN,2.025091e+13,NaN,NaN,NaN,NaN,NaN,NaN,5.014931e+08,...,5.000000,4.970000,4.890000,NaN,NaN,6.000000,3.000000,2.000000,0.000000,2.650000
max,1.509455e+18,NaN,2.025091e+13,NaN,NaN,NaN,NaN,NaN,NaN,7.187550e+08,...,5.000000,5.000000,5.000000,NaN,NaN,252.000000,252.000000,43.000000,18.000000,40.250000

#### 2.2 Reviews dataframe

In [8]:
reviews_raw.head(8)

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,2737,24343517,2014-12-26,24333039,Raphaell,"This spot was in a great and nice area,walking..."
1,2737,24966779,2015-01-04,10493776,Ia,"Elif was really very helpful, while arranging ..."
2,2737,29770086,2015-04-12,29630601,Julia,"Elif's flat is spacious, clean, and had everyt..."
3,2737,30477570,2015-04-22,31215535,Sevil,I had a wonderful time staying with Elif and h...
4,2737,31659336,2015-05-08,1959813,Suzy,"Elif was a brilliant host, with an exceptional..."
5,11834,246099,2011-05-01,346365,Joanne,We loved our stay at Boschetto House. It was a...
6,11834,343799,2011-06-30,388909,Eteri,Everything was perfect! The apartment in a per...
7,11834,529617,2011-09-13,953228,Ginger,Apartment: Very nicely set up for guests - wel...

In [9]:
reviews_raw.shape

(2193330, 6)

In [10]:
reviews_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 2193330 entries, 0 to 2193329
Data columns (total 6 columns):
 #   Column         Dtype
---  ------         -----
 0   listing_id     int64
 1   id             int64
 2   date           str
 3   reviewer_id    int64
 4   reviewer_name  str
 5   comments       str
dtypes: int64(3), str(3)
memory usage: 100.4 MB

In [11]:
reviews_raw.describe(include = 'all')

,listing_id,id,date,reviewer_id,reviewer_name,comments
count,2.193330e+06,2.193330e+06,2193330,2.193330e+06,2193326,2193194
unique,NaN,NaN,5242,NaN,210331,2128354
top,NaN,NaN,2025-06-15,NaN,David,.
freq,NaN,NaN,3059,NaN,12442,3364
mean,2.786899e+17,7.687826e+17,NaN,1.988914e+08,NaN,NaN
std,4.496493e+17,5.411816e+17,NaN,1.838539e+08,NaN,NaN
min,2.737000e+03,4.220600e+04,NaN,4.600000e+01,NaN,NaN
25%,9.950970e+06,5.757394e+08,NaN,4.574577e+07,NaN,NaN
50%,2.920817e+07,9.099389e+17,NaN,1.344782e+08,NaN,NaN
75%,6.590309e+17,1.238298e+18,NaN,3.235647e+08,NaN,NaN
max,1.507195e+18,1.510885e+18,NaN,7.187870e+08,NaN,NaN